stages:
    - build
    - test
    - deploy
    
build_job:
    stage: build
    script: echo "Build!"
        
test_job:
    stage: test
    script:
        - echo "Test!"
        
deploy_job:
    stage: deploy
    script:
        - echo "Deploy!"
